(() => {
 'use strict';
 const $=s=>document.querySelector(s),M=window.ACMath,lessons=window.ACLessons;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem('ac-'+key));return v===null?fallback:v;}catch{return fallback;}};
 let storageWarned=false;const write=(key,value)=>{try{localStorage.setItem('ac-'+key,JSON.stringify(value));}catch{if(!storageWarned){storageWarned=true;toast('Storage unavailable. History will last for this session.');}}};
 const validHistory=read('history',[]),validProgress=read('progress',{});
 const state={route:'calculator',calcMode:'scientific',expression:'sqrt(144) + 3^2',answer:'21',ans:21,angle:read('angle','deg')==='rad'?'rad':'deg',theme:read('theme','light')==='dark'?'dark':'light',history:Array.isArray(validHistory)?validHistory.filter(x=>x&&typeof x.id==='string'&&typeof x.input==='string'&&typeof x.answer==='string').slice(0,200):[],progress:validProgress&&typeof validProgress==='object'&&!Array.isArray(validProgress)?validProgress:{},equation:'x^2 - 5x + 6 = 0',solverMode:'equation',systemN:2,systemInputs:['x + y = 7','x - y = 1','x + y + z = 6'],lesson:null,practiceIndex:0,historyFilter:'all',historySearch:'',graphExpression:'x^2 - 4',xmin:-5,xmax:5,complexInputs:[2,3,1,-1],complexOp:'*'};
 let lastSolution=null,toastTimer,graphResult=null;
 function fmt(v,d=10){if(!Number.isFinite(v))return 'Out of range';if(v===0)return '0';return Number(v.toPrecision(d)).toString();}
 function zfmt({re,im}){if(Math.abs(im)===0)return fmt(re);const imag=(Math.abs(im)===1?'':fmt(Math.abs(im)))+'i';return re===0?(im<0?'-':'')+imag:fmt(re)+(im<0?' − ':' + ')+imag;}
 function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
 function save(entry){const id=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);state.history.unshift({...entry,id,date:new Date().toISOString(),star:false});state.history=state.history.slice(0,200);write('history',state.history);return id;}
 async function copy(text){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{let el=document.createElement('textarea');el.value=text;el.style.position='fixed';el.style.opacity='0';document.body.append(el);el.select();const ok=document.execCommand('copy');el.remove();if(!ok)throw Error();}toast('Copied to clipboard.');}catch{toast('Clipboard unavailable in this browser.');}}
 function head(title,desc,kicker='MATH WORKSPACE',right=''){return `<div class="page-heading"><div><span class="section-kicker">${kicker}</span><h1>${title}</h1><p>${desc}</p></div>${right}</div>`;}
 function error(target,e){$(target).innerHTML=`<div class="error" role="alert">${esc(e.message||e)}</div>`;}
 function recent(){return state.history.slice(0,3).map(h=>`<div class="recent-row"><div><div class="math-text">${esc(h.input)}</div><small>${esc(h.kind)}</small></div><strong>${esc(h.answer)}</strong></div>`).join('')||'<p class="empty-mini">Your next calculation will appear here. Results are saved when you press = or Solve.</p>';}
 function calcRight(){return `<div class="stack"><section class="feature-card"><span class="eyebrow">MORE THAN AN ANSWER</span><h2>See how the<br>solution unfolds.</h2><p>Follow each step from your equation to its roots.</p><div class="feature-formula">x² − 5x + 6 = 0</div><a class="primary" href="#solver">Open equation solver</a></section><section class="card"><div class="card-body" style="padding-top:23px"><div class="mini-heading"><h2>Recent calculations</h2><a class="text-link" href="#history">View all</a></div><div id="recent-calculations">${recent()}</div></div></section></div>`;}
 function calculator(){
  const keys=[['sin','sin(','function'],['cos','cos(','function'],['tan','tan(','function'],['(', '(','function'],[')',')','function'],['ln','ln(','function'],['log','log(','function'],['√','sqrt(','function'],['xʸ','^','function'],['n!','!','function'],['AC','clear','danger'],['⌫','backspace','function'],['%','%','function'],['π','pi','function'],['÷','/','operator'],['7','7',''],['8','8',''],['9','9',''],['x²','^2','function'],['×','*','operator'],['4','4',''],['5','5',''],['6','6',''],['e','e','function'],['−','-','operator'],['1','1',''],['2','2',''],['3','3',''],['Ans','ans','function'],['+','+','operator'],['0','0',''],['.','.',''],['±','sign','function'],['1/x','reciprocal','function'],['=','equals','equal']];
  return head('A clearer way to calculate.','Your everyday math, with room for the harder questions.','CALCULATOR','<span class="pill">Works offline after first load</span>')+`<div class="grid-work"><section class="card"><div class="card-head"><h2>Calculator</h2><div class="tabs" aria-label="Calculator mode"><button data-action="calc-mode" data-mode="scientific" class="${state.calcMode==='scientific'?'active':''}">Scientific</button><button data-action="calc-mode" data-mode="complex" class="${state.calcMode==='complex'?'active':''}">Complex</button></div></div>${state.calcMode==='scientific'?`<div class="calc-screen"><div class="screen-top"><span>EXPRESSION</span><span id="screen-angle">${state.angle.toUpperCase()} MODE</span></div><input class="expression" id="calc-expression" aria-label="Calculation expression" value="${esc(state.expression)}" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Enter an expression"><output class="screen-answer" id="calc-answer" aria-live="polite">${esc(state.answer)}</output></div><div class="calc-toolbar"><div class="angle-control"><button data-action="angle" data-angle="deg" class="${state.angle==='deg'?'active':''}">DEG</button><button data-action="angle" data-angle="rad" class="${state.angle==='rad'?'active':''}">RAD</button></div><span>Rounded to 10 significant digits</span><button class="text-link" data-action="copy-calc">Copy</button></div><div class="keypad">${keys.map(([label,key,cls])=>`<button class="key ${cls}" data-action="key" data-key="${esc(key)}" aria-label="${esc(key==='backspace'?'Delete last character':key==='equals'?'Calculate':label)}">${label}</button>`).join('')}</div><div id="calc-error" style="padding:0 20px 15px" hidden></div><div class="calc-hint"><span>ⓘ</span>Type or tap. Use brackets for grouping; % divides by 100.</div>`:complexForm()}</section>${calcRight()}</div><div class="quick-tools"><a class="quick-tool" href="#solver"><span class="tool-icon">x²</span><div><strong>Find the roots</strong><small>Linear & quadratic equations</small></div></a><a class="quick-tool" href="#graph"><span class="tool-icon">⌁</span><div><strong>Plot a function</strong><small>Explore its shape</small></div></a><a class="quick-tool" href="#learn"><span class="tool-icon">▤</span><div><strong>Build your understanding</strong><small>8 lessons · 24 questions</small></div></a></div>`;
 }
 function complexForm(){return `<div class="card-body"><p class="subtext" style="margin-bottom:24px">Enter each number as a real part and an imaginary coefficient.</p><label class="form-label">First number · a + bi</label><div class="form-row">${[0,1].map(i=>`<div><input class="field" id="complex-${i}" type="number" step="any" value="${esc(state.complexInputs[i])}" aria-label="${i?'First imaginary coefficient':'First real part'}"><p class="field-note">${i?'Imaginary coefficient (b)':'Real part (a)'}</p></div>`).join('')}</div><label class="form-label" for="complex-op">Operation</label><select id="complex-op" class="field" style="margin-bottom:24px">${[['+','Add'],['-','Subtract'],['*','Multiply'],['/','Divide']].map(([v,t])=>`<option value="${v}" ${v===state.complexOp?'selected':''}>${t}</option>`).join('')}</select><label class="form-label">Second number · c + di</label><div class="form-row">${[2,3].map(i=>`<div><input class="field" id="complex-${i}" type="number" step="any" value="${esc(state.complexInputs[i])}" aria-label="${i===3?'Second imaginary coefficient':'Second real part'}"><p class="field-note">${i===3?'Imaginary coefficient (d)':'Real part (c)'}</p></div>`).join('')}</div><button class="primary full-width" data-action="complex-solve">Calculate complex result</button><div id="complex-error"></div><div id="complex-result"></div></div>`;}
 function support(){return `<div class="stack"><section class="card"><div class="card-head"><h2>What can I solve?</h2></div><div class="card-body"><div class="support-list"><div class="support-item"><span class="support-icon">✓</span><div><b>Linear equations</b>Variables on either side, brackets and fractional coefficients.</div></div><div class="support-item"><span class="support-icon">✓</span><div><b>Quadratic equations</b>Two real roots, repeated roots and complex conjugate roots.</div></div><div class="support-item"><span class="support-icon">✓</span><div><b>Linear systems</b>2 or 3 variables, with row operations and numerical checks.</div></div></div><p class="field-note" style="margin-top:24px">Use ^ for powers and * for multiplication. Variable denominators, functions of variables and higher-degree polynomials are outside this solver’s scope.</p></div></section><section class="feature-card"><span class="eyebrow">UNDERSTAND THE METHOD</span><h2>Why does the<br>discriminant matter?</h2><p>It tells you what kind of roots a quadratic has, before you calculate them.</p><div class="feature-formula">D = b² − 4ac</div><button class="primary" data-action="open-lesson" data-id="quadratic">Read the lesson</button></section></div>`;}
 function solver(){return head('Every solution has a story.','Enter an equation. Follow the method. Check the result.','EQUATION SOLVER')+`<div class="grid-work"><div><section class="card"><div class="card-head"><h2>Solve with steps</h2><div class="tabs"><button data-action="solver-mode" data-mode="equation" class="${state.solverMode==='equation'?'active':''}">Equation</button><button data-action="solver-mode" data-mode="system" class="${state.solverMode==='system'?'active':''}">System</button></div></div><div class="card-body">${state.solverMode==='equation'?`<label class="form-label" for="equation-input">Your equation</label><input id="equation-input" class="field equation-input" value="${esc(state.equation)}" spellcheck="false" autocapitalize="off" autocomplete="off"><p class="field-note">Solve for x · Linear and quadratic polynomials · If = is omitted, the right side is 0.</p><div class="example-chips">${['3x + 7 = 22','x^2 + 4 = 0','2(x - 1) = 3x + 4'].map(e=>`<button data-action="example-equation" data-value="${esc(e)}">${esc(e)}</button>`).join('')}</div><div class="form-actions"><button class="primary" data-action="solve-equation">Solve equation</button><button class="secondary" data-action="reset-equation">Clear</button></div>`:`<div class="row" style="justify-content:space-between;margin-bottom:22px"><p class="subtext">Linear equations only</p><div class="tabs"><button data-action="system-count" data-count="2" class="${state.systemN===2?'active':''}">2 variables</button><button data-action="system-count" data-count="3" class="${state.systemN===3?'active':''}">3 variables</button></div></div><div class="system-fields">${Array.from({length:state.systemN},(_,i)=>`<div><label class="form-label" for="system-${i}">Equation ${i+1}</label><input id="system-${i}" class="field" value="${esc(state.systemInputs[i])}" spellcheck="false" autocapitalize="off"></div>`).join('')}</div><p class="field-note">Use ${state.systemN===2?'x and y':'x, y and z'}. Both sides may contain variables.</p><div class="form-actions"><button class="primary" data-action="solve-system">Solve system</button><button class="secondary" data-action="example-system">Load example</button></div>`}<div id="solver-error"></div></div></section><div id="solution"></div></div>${support()}</div>`;}
 function step(title,detail,math,index){return `<div class="step"><span class="step-number">${index}</span><div><h3>${title}</h3>${detail?`<p>${detail}</p>`:''}${math?`<div class="math-text">${math}</div>`:''}</div></div>`;}
 function polyText(co){const [c,b,a]=co;let s='';[[a,'x²'],[b,'x'],[c,'']].forEach(([v,p])=>{if(v===0)return;let magnitude=Math.abs(v),term=(p&&magnitude===1?'':fmt(magnitude))+p;s+=(s?(v<0?' − ':' + '):(v<0?'−':''))+term;});return (s||'0')+' = 0';}
 function equationResult(s){const [c,b,a]=s.co;let steps=[],answers=s.roots.map(r=>'x = '+zfmt(r)),meta='';steps.push(step('Bring the equation to standard form','Subtract the right-hand side and collect the coefficients.',esc(polyText(s.co)),1));
  if(s.type==='identity'||s.type==='none'){answers=[s.type==='identity'?'Every real x satisfies this equation':'No solution'];meta=s.type==='identity'?'Both sides simplify to the same expression.':'The variable cancels, leaving a false statement.';steps.push(step('Compare the constant terms',meta,esc(fmt(c)+' = 0'),2));}
  else if(s.type==='linear'){meta='One real solution';steps.push(step('Isolate the variable','Subtract the constant term, then divide by the x coefficient.',`${esc(fmt(b))}x = ${esc(fmt(-c))}<br>x = ${esc(fmt(-c))} / (${esc(fmt(b))}) = ${esc(fmt(s.roots[0].re))}`,2));steps.push(step('Substitute and check','Putting the result into the collected expression should give zero.',`${esc(fmt(b))} × (${esc(fmt(s.roots[0].re))}) + (${esc(fmt(c))}) ≈ 0`,3));}
  else {const rawD=b*b-4*a*c,normalized=!Number.isFinite(rawD),A=normalized?a/s.scale:a,B=normalized?b/s.scale:b,C=normalized?c/s.scale:c,D=normalized?s.discriminant:rawD;meta=({complex:'Two complex conjugate roots',repeated:'One repeated real root',quadratic:'Two distinct real roots'})[s.type];
   steps.push(step('Identify a, b and c',normalized?'Divide all coefficients by their largest magnitude to avoid overflow.':'Read the coefficients of x², x and the constant.',`a = ${esc(fmt(A))} &nbsp; b = ${esc(fmt(B))} &nbsp; c = ${esc(fmt(C))}`,2));
   steps.push(step('Calculate the discriminant','Its sign determines the type of roots.',`D = b² − 4ac<br>D = (${esc(fmt(B))})² − 4(${esc(fmt(A))})(${esc(fmt(C))}) = ${esc(fmt(D))}`,3));
   steps.push(step('Apply the quadratic formula',s.type==='complex'?'The negative discriminant introduces i, where i² = −1.':'Use both the plus and minus branches.',`x = (−b ± √D) / (2a)<br>x = (${esc(fmt(-B))} ± ${D<0?esc(fmt(Math.sqrt(-D)))+'i':'√('+esc(fmt(D))+')'}) / (${esc(fmt(2*A))})`,4));
   steps.push(step('Simplify the roots','Results are rounded for display; the numerical check uses unrounded values.',answers.map(esc).join('<br>'),5));
  }
  const ok=s.type==='linear'||(s.residuals&&s.residuals.every(v=>v<1e-8));
  lastSolution={input:state.equation,answer:answers.join('; '),kind:'Equation',copy:state.equation+'\n'+answers.join('\n')+'\n'+meta};
  return `<section class="card result-card"><div class="result-hero"><div class="result-heading"><span>SOLUTION</span><button class="text-link" data-action="copy-solution">Copy result</button></div><div class="answer-pills">${answers.map(t=>`<span class="answer-pill">${esc(t)}</span>`).join('')}</div><p class="result-meta">${meta}</p></div><div class="steps">${steps.join('')}</div>${s.roots.length?`<div class="verification ${ok?'':'warn'}">${ok?'✓ Numerically checked against the equation.':'Check precision: the numerical residual is larger than expected.'} Displayed answers use up to 10 significant digits.</div>`:''}</section>`;
 }
 function runEquation(record=true){try{state.equation=$('#equation-input').value.trim();$('#solver-error').innerHTML='';const s=M.solve(state.equation);$('#solution').innerHTML=equationResult(s);if(record){save(lastSolution);toast('Solution saved to history.');}}catch(e){$('#solution').innerHTML='';lastSolution=null;error('#solver-error',e);}}
 function matrixHTML(m){return `<div class="matrix" aria-label="Augmented coefficient matrix">${m.map(row=>`<div class="matrix-row">${row.map(v=>`<span>${esc(fmt(v,6))}</span>`).join('')}</div>`).join('')}</div>`;}
 function runSystem(){try{state.systemInputs=Array.from({length:state.systemN},(_,i)=>$('#system-'+i).value.trim());$('#solver-error').innerHTML='';const s=M.system(state.systemInputs);let answer=s.type==='unique'?s.variables.map((v,i)=>v+' = '+fmt(s.solution[i])).join('; '):s.type==='none'?'No solution':'Infinitely many solutions';lastSolution={kind:'Linear system',input:state.systemInputs.join(' · '),answer,copy:state.systemInputs.join('\n')+'\n'+answer};
  const status=s.type==='unique'?'A unique solution':s.type==='none'?'The equations are inconsistent.':'The equations do not determine a unique value for every variable.';
  $('#solution').innerHTML=`<section class="card result-card"><div class="result-hero"><div class="result-heading"><span>SYSTEM SOLUTION</span><button class="text-link" data-action="copy-solution">Copy result</button></div><div class="answer-pills">${(s.type==='unique'?s.variables.map((v,i)=>v+' = '+fmt(s.solution[i])):[answer]).map(v=>`<span class="answer-pill">${esc(v)}</span>`).join('')}</div><p class="result-meta">${status}</p></div><div class="steps">${step('Build the augmented matrix','The final column contains constants on the right-hand side.',matrixHTML(s.original),1)}${s.steps.map((st,i)=>step(st.text,'Row scaling and elimination keep the system equivalent.',matrixHTML(st.matrix),i+2)).join('')}${s.type!=='unique'?step('Interpret the reduced system',s.type==='none'?'A row has zero variable coefficients but a nonzero constant. It cannot be satisfied.':'At least one variable is free because there are fewer independent equations than unknowns.','',s.steps.length+2):''}</div>${s.type==='unique'?`<div class="verification ${s.residuals.every(v=>v<1e-8)?'':'warn'}">${s.residuals.every(v=>v<1e-8)?'✓ All original equations passed the numerical residual check.':'The system may be ill-conditioned; verify with a higher-precision tool.'}</div>`:''}</section>`;save(lastSolution);toast('System saved to history.');
 }catch(e){$('#solution').innerHTML='';lastSolution=null;error('#solver-error',e);}}
 function complexSolve(){try{state.complexInputs=Array.from({length:4},(_,i)=>{let v=$('#complex-'+i).value;if(v.trim()===''||!Number.isFinite(Number(v)))throw Error('Enter a finite number in each field.');return Number(v);});state.complexOp=$('#complex-op').value;const [a,b,c,d]=state.complexInputs,r=M.complex([a,b],[c,d],state.complexOp),input=`(${zfmt({re:a,im:b})}) ${({'*':'×','/':'÷'})[state.complexOp]||state.complexOp} (${zfmt({re:c,im:d})})`;let explanation=state.complexOp==='*'?`Real: ac − bd = (${fmt(a)})(${fmt(c)}) − (${fmt(b)})(${fmt(d)})<br>Imaginary: ad + bc = (${fmt(a)})(${fmt(d)}) + (${fmt(b)})(${fmt(c)})`:state.complexOp==='/'?'Multiply numerator and denominator by the conjugate of the second number. The denominator becomes c² + d².':'Combine the real parts and imaginary coefficients separately.';
  $('#complex-error').innerHTML='';$('#complex-result').innerHTML=`<div class="complex-answer"><h3>COMPLEX RESULT</h3><div class="math-text">${esc(zfmt(r))}</div><p class="subtext">Magnitude: ${esc(fmt(r.magnitude))}<br>Conjugate: ${esc(zfmt({re:r.re,im:-r.im}))}</p></div><div class="steps" style="padding-left:0;padding-right:0">${step('Apply the operation',state.complexOp==='*'?'Expand the brackets and use i² = −1.':'',explanation,1)}${step('Collect both components','Real and imaginary parts are tracked independently.',`Real part = ${esc(fmt(r.re))}<br>Imaginary coefficient = ${esc(fmt(r.im))}`,2)}</div>`;save({kind:'Complex number',input,answer:zfmt(r),components:[...state.complexInputs],operation:state.complexOp});$('#recent-calculations').innerHTML=recent();toast('Calculation saved.');
 }catch(e){$('#complex-result').innerHTML='';error('#complex-error',e);}}
 function graph(){return head('Give your function a shape.','Explore real-valued functions across an adjustable interval.','GRAPH EXPLORER')+`<section class="card"><div class="card-head"><h2>Function plot</h2><div class="graph-controls"><button class="secondary" data-action="graph-zoom" data-factor="0.5" aria-label="Zoom in">+</button><button class="secondary" data-action="graph-zoom" data-factor="2" aria-label="Zoom out">−</button><button class="secondary" data-action="graph-reset">Reset</button></div></div><div class="graph-form"><div><label class="form-label" for="graph-expression">y = f(x)</label><input id="graph-expression" class="field" value="${esc(state.graphExpression)}" spellcheck="false" autocapitalize="off"></div><div><label class="form-label" for="graph-min">x minimum</label><input id="graph-min" class="field" type="number" step="any" value="${state.xmin}"></div><div><label class="form-label" for="graph-max">x maximum</label><input id="graph-max" class="field" type="number" step="any" value="${state.xmax}"></div><button class="primary" data-action="plot">Plot function</button></div><div id="graph-error" style="padding:0 24px"></div><div class="graph-viewport"><svg id="graph-svg" class="graph-svg" viewBox="0 0 900 430" role="img" aria-label="Function graph"></svg></div><div class="graph-meta"><div class="legend" id="graph-legend"></div><span id="graph-coordinate">Move over the plot to inspect coordinates</span><span id="graph-range"></span></div><div class="graph-presets"><span class="form-label">Try a function</span><div class="example-chips">${['x^2 - 4','sin(x)','1/x','sqrt(x)','2x + 3'].map(f=>`<button data-action="graph-preset" data-value="${esc(f)}">${esc(f)}</button>`).join('')}</div><p class="field-note">Trigonometric graphs use radians. The y-range adapts to sampled values. Plot segments near asymptotes are suppressed; a sampled graph cannot prove exact roots or continuity.</p><button class="text-link" data-action="save-graph" style="margin-top:12px">Save this graph to history</button></div></section>`;}
 function plot(){try{state.graphExpression=$('#graph-expression').value.trim();const minText=$('#graph-min').value,maxText=$('#graph-max').value;if(!minText.trim()||!maxText.trim())throw Error('Enter both ends of the x interval.');let lo=Number(minText),hi=Number(maxText);if(!Number.isFinite(lo)||!Number.isFinite(hi)||hi<=lo||hi-lo<1e-8||Math.max(Math.abs(lo),Math.abs(hi))>1e6)throw Error('Use an increasing interval at least 0.00000001 wide, within ±1,000,000.');
  const ast=M.parse(state.graphExpression),N=800,points=[];for(let i=0;i<=N;i++){const x=lo+(hi-lo)*i/N;let y;try{y=M.evaluate(ast,{x},'rad');if(Math.abs(y)>1e100)y=NaN;}catch{y=NaN;}points.push({x,y});}
  const ys=points.filter(p=>Number.isFinite(p.y)).map(p=>p.y).sort((a,b)=>a-b);if(ys.length<2)throw Error('No usable real-valued points in this interval. Check the function and its domain.');let low=ys[Math.floor(ys.length*.03)],high=ys[Math.min(ys.length-1,Math.floor(ys.length*.97))];if(high-low<1e-10){low-=1;high+=1;}const pad=(high-low)*.13;low-=pad;high+=pad;state.xmin=lo;state.xmax=hi;
  const W=900,H=430,L=62,R=23,T=22,B=39,pw=W-L-R,ph=H-T-B,px=x=>L+(x-lo)/(hi-lo)*pw,py=y=>T+(high-y)/(high-low)*ph;
  let markup='<defs><clipPath id="plot-clip"><rect x="62" y="22" width="815" height="369"/></clipPath></defs>';const ink=state.theme==='dark'?'#8494b0':'#8090a9',line=state.theme==='dark'?'#293950':'#e1e7f0';for(let i=0;i<=8;i++){let x=lo+(hi-lo)*i/8,y=low+(high-low)*i/8;markup+=`<line x1="${px(x)}" y1="${T}" x2="${px(x)}" y2="${H-B}" stroke="${line}"/><line x1="${L}" y1="${py(y)}" x2="${W-R}" y2="${py(y)}" stroke="${line}"/><text x="${px(x)}" y="${H-12}" text-anchor="middle" fill="${ink}" font-size="13" font-family="sans-serif">${esc(fmt(x,4))}</text><text x="${L-10}" y="${py(y)+4}" text-anchor="end" fill="${ink}" font-size="13" font-family="sans-serif">${esc(fmt(y,4))}</text>`;}
  if(lo<=0&&hi>=0)markup+=`<line x1="${px(0)}" y1="${T}" x2="${px(0)}" y2="${H-B}" stroke="${ink}" stroke-width="1.3"/>`;if(low<=0&&high>=0)markup+=`<line x1="${L}" y1="${py(0)}" x2="${W-R}" y2="${py(0)}" stroke="${ink}" stroke-width="1.3"/>`;
  let path='',prev=null;for(const p of points){if(!Number.isFinite(p.y)){prev=null;continue;}const jump=prev&&Math.abs(py(p.y)-py(prev.y))>ph*.7;path+=(prev&&!jump?'L':'M')+px(p.x).toFixed(2)+','+py(p.y).toFixed(2);prev=p;}
  markup+=`<path d="${path}" fill="none" stroke="${state.theme==='dark'?'#8aaeff':'#376ae8'}" stroke-width="3" clip-path="url(#plot-clip)"/><g id="graph-cursor" visibility="hidden"><line id="cursor-line" y1="${T}" y2="${H-B}" stroke="${ink}" stroke-dasharray="5 5"/><circle id="cursor-point" r="5" fill="#376ae8" stroke="white" stroke-width="2"/></g>`;
  $('#graph-svg').innerHTML=markup;$('#graph-error').innerHTML='';$('#graph-legend').textContent='y = '+state.graphExpression;$('#graph-range').textContent=`${fmt(low,4)} ≤ y ≤ ${fmt(high,4)}`;graphResult={ast,lo,hi,low,high,px,py,L,pw};
  $('#graph-svg').onpointermove=e=>{const svg=$('#graph-svg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const q=pt.matrixTransform(svg.getScreenCTM().inverse()),x=lo+(q.x-L)/pw*(hi-lo);if(x<lo||x>hi){$('#graph-cursor').setAttribute('visibility','hidden');return;}try{const y=M.evaluate(ast,{x},'rad');$('#graph-coordinate').textContent=`x ≈ ${fmt(x,6)} · y ≈ ${fmt(y,6)}`;$('#cursor-line').setAttribute('x1',px(x));$('#cursor-line').setAttribute('x2',px(x));$('#cursor-point').setAttribute('cx',px(x));$('#cursor-point').setAttribute('cy',py(y));$('#cursor-point').setAttribute('visibility',y<low||y>high?'hidden':'visible');$('#graph-cursor').setAttribute('visibility','visible');}catch{$('#graph-coordinate').textContent='Function is undefined here.';$('#graph-cursor').setAttribute('visibility','hidden');}};
 }catch(e){graphResult=null;$('#graph-svg').innerHTML='';$('#graph-legend').textContent='';$('#graph-range').textContent='';error('#graph-error',e);}}
 function progressStats(){const correct=Object.values(state.progress).filter(v=>v&&v.correct).length;const attempted=Object.values(state.progress).filter(v=>v&&v.attempted).length;return {correct,attempted};}
 function learn(){const p=progressStats();if(state.lesson)return lessonDetail();return head('Make the method yours.','Short explanations, worked examples and questions to try.','LEARN & PRACTICE')+`<div class="stats-strip"><div class="card stat"><strong>8</strong><span>Focused lessons</span></div><div class="card stat"><strong>${p.correct} / 24</strong><span>Questions mastered</span></div><div class="card stat"><strong>${p.attempted}</strong><span>Questions attempted</span></div></div><div class="lesson-grid">${lessons.map(l=>{const n=l.practice.filter((_,i)=>state.progress[l.id+'-'+i]?.correct).length;return `<button class="card lesson-card" data-action="open-lesson" data-id="${l.id}" style="text-align:left"><span class="tool-icon">${l.icon}</span><h2>${l.title}</h2><p>${l.intro}</p><div class="lesson-foot"><span>${l.tag} · ${l.time}</span><span class="${n===3?'success-label':''}">${n}/3 practiced</span></div></button>`;}).join('')}</div>`;}
 function lessonDetail(){const l=lessons.find(x=>x.id===state.lesson)||lessons[0],i=state.practiceIndex%l.practice.length,q=l.practice[i],completed=l.practice.filter((_,j)=>state.progress[l.id+'-'+j]?.correct).length;return head(l.title,l.intro,'LEARN & PRACTICE',`<button class="secondary" data-action="back-lessons">All lessons</button>`)+`<button class="text-link" data-action="back-lessons" style="margin-bottom:18px">All lessons</button><div class="grid-work"><article class="card lesson-detail"><span class="eyebrow" style="color:var(--accent)">${l.tag.toUpperCase()} · ${l.time.toUpperCase()}</span><h2>The idea</h2><p>${l.explain}</p><div class="formula-box">${esc(l.formula).replace(/\n/g,'<br>')}</div><h2>${l.example}</h2><ol>${l.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="lesson-callout"><p>${l.tip}</p></div><button class="secondary" data-action="lesson-tool" data-id="${l.id}">Try it in the calculator</button></article><section class="card practice-card"><div class="mini-heading"><h2>Your turn</h2><span class="pill">${i+1} / ${l.practice.length}</span></div><div class="progress-track"><span style="width:${completed/3*100}%"></span></div><p class="subtext">${completed} of 3 mastered · Enter a number, fraction or expression.</p><p class="practice-question">${esc(q.q)}</p><label class="form-label" for="practice-answer">Your answer</label><input class="field" id="practice-answer" autocomplete="off" spellcheck="false" placeholder="e.g. 5 or 1/2"><div class="form-actions"><button class="primary" data-action="check-practice">Check answer</button><button class="secondary" data-action="next-practice">Next</button></div><div id="practice-feedback" aria-live="polite"></div><p class="field-note" style="margin-top:20px">Practice progress is saved on this device. A question counts as mastered after a correct answer.</p></section></div>`;}
 function checkPractice(){const l=lessons.find(x=>x.id===state.lesson),i=state.practiceIndex%3,q=l.practice[i],key=l.id+'-'+i;try{const v=M.evaluate(M.parse($('#practice-answer').value),{},'rad'),ok=Math.abs(v-q.a)<=1e-8*Math.max(1,Math.abs(q.a));state.progress[key]={attempted:true,correct:ok||!!state.progress[key]?.correct};write('progress',state.progress);$('#practice-feedback').innerHTML=`<div class="feedback ${ok?'correct':'incorrect'}"><strong>${ok?'Correct.':'Try this method.'}</strong><br>${esc(q.ex)}</div>`;const n=l.practice.filter((_,j)=>state.progress[l.id+'-'+j]?.correct).length;$('.progress-track span').style.width=n/3*100+'%';$('.practice-card>.subtext').textContent=`${n} of 3 mastered · Enter a number, fraction or expression.`;}catch(e){$('#practice-feedback').innerHTML=`<div class="error" role="alert">${esc(e.message)}</div>`;}}
 function history(){const p=progressStats(),count=state.history.length;return head('Keep the useful work.','Revisit a result or bookmark it for your next study session.','SAVED & HISTORY',`<button class="secondary" data-action="clear-history">Clear history</button>`)+`<div class="stats-strip"><div class="card stat"><strong>${count}</strong><span>Saved calculations</span></div><div class="card stat"><strong>${state.history.filter(h=>h.star).length}</strong><span>Bookmarked results</span></div><div class="card stat"><strong>${p.correct}</strong><span>Practice questions mastered</span></div></div><div class="history-controls"><input class="field" id="history-search" placeholder="Search calculations…" aria-label="Search history" value="${esc(state.historySearch)}"><div class="tabs"><button data-action="history-filter" data-filter="all" class="${state.historyFilter==='all'?'active':''}">All results</button><button data-action="history-filter" data-filter="saved" class="${state.historyFilter==='saved'?'active':''}">Bookmarks</button></div></div><div class="history-list" id="history-list">${historyRows()}</div><div style="margin-top:25px"><button class="text-link" data-action="reset-progress">Reset practice progress</button></div>`;}
 function historyRows(){const items=state.history.filter(h=>(state.historyFilter!=='saved'||h.star)&&[h.input,h.answer,h.kind].join(' ').toLowerCase().includes(state.historySearch.toLowerCase()));if(!items.length)return `<section class="card empty-state"><span class="tool-icon">◷</span><h2>${state.historySearch?'No matching results':state.historyFilter==='saved'?'No bookmarks yet':'A fresh page for your work.'}</h2><p>${state.historyFilter==='saved'?'Tap the star beside a result to keep it handy.':'Saved calculations appear here. Your history stays on this device.'}</p><a class="primary" href="#calculator">Open calculator</a></section>`;return items.map(h=>`<article class="card history-item"><span class="tool-icon">${h.kind==='Graph'?'⌁':h.kind==='Equation'?'x²':h.kind==='Complex number'?'i':'='}</span><div class="history-main"><div class="math-text">${esc(h.input)}</div><strong>${esc(h.answer)}</strong><p class="history-meta">${esc(h.kind)} · ${esc(Number.isNaN(Date.parse(h.date))?'Saved result':new Date(h.date).toLocaleDateString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</p><button class="text-link" data-action="reuse" data-id="${esc(h.id)}">${h.kind==='Graph'?'Open graph':'Use again'}</button></div><div class="history-actions"><button class="icon-button ${h.star?'starred':''}" data-action="star" data-id="${esc(h.id)}" aria-label="${h.star?'Remove bookmark':'Bookmark result'}" aria-pressed="${!!h.star}">${h.star?'★':'☆'}</button><button class="icon-button" data-action="copy-history" data-id="${esc(h.id)}" aria-label="Copy result">⧉</button><button class="icon-button" data-action="delete-history" data-id="${esc(h.id)}" aria-label="Delete result">×</button></div></article>`).join('');}
 function render(){document.body.classList.toggle('dark',state.theme==='dark');$('#theme-button').textContent=state.theme==='dark'?'☀':'☾';$('#theme-button').setAttribute('aria-label',state.theme==='dark'?'Switch to light theme':'Switch to dark theme');const titles={calculator:'Calculator',solver:'Equation solver',graph:'Graphs',learn:'Learn & practice',history:'Saved & history'};$('#breadcrumb-title').textContent=titles[state.route];document.querySelectorAll('[data-route]').forEach(el=>{const active=el.dataset.route===state.route;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});$('#content').innerHTML=({calculator,solver,graph,learn,history})[state.route]();if(state.route==='graph')plot();if(state.route==='solver'&&state.solverMode==='equation'&&state.equation)runEquation(false);}
 function route(){const hash=location.hash.slice(1);state.route=['calculator','solver','graph','learn','history'].includes(hash)?hash:'calculator';render();window.scrollTo(0,0);}
 function capture(){if($('#calc-expression'))state.expression=$('#calc-expression').value;if($('#equation-input'))state.equation=$('#equation-input').value;if($('#system-0'))state.systemInputs=Array.from({length:state.systemN},(_,i)=>$('#system-'+i).value);if($('#complex-0')){state.complexInputs=Array.from({length:4},(_,i)=>$('#complex-'+i).value);state.complexOp=$('#complex-op').value;}}
 function calculate(record=true){const input=$('#calc-expression');state.expression=input.value;const box=$('#calc-error');try{const v=M.evaluate(M.parse(state.expression),{},state.angle);state.answer=fmt(v);$('#calc-answer').textContent=state.answer;box.hidden=true;box.innerHTML='';if(record){state.ans=v;save({kind:'Scientific · '+state.angle.toUpperCase(),input:state.expression,answer:state.answer});$('#recent-calculations').innerHTML=recent();}}catch(e){state.answer='—';$('#calc-answer').textContent='—';box.hidden=false;error('#calc-error',e);}}
 function dirty(){state.answer='—';if($('#calc-answer'))$('#calc-answer').textContent='—';if($('#calc-error'))$('#calc-error').hidden=true;}
 function key(k){const input=$('#calc-expression');if(k==='equals'){calculate();return;}let v=input.value,start=input.selectionStart??v.length,end=input.selectionEnd??v.length,insert=k;dirty();
  if(k==='clear'){input.value='';state.expression='';state.answer='0';$('#calc-answer').textContent='0';$('#calc-error').hidden=true;input.focus();return;}
  if(k==='backspace'){if(start===end&&start>0)start--;insert='';}
  if(k==='ans')insert='('+fmt(state.ans,15)+')';if(k==='sign'){input.value=v?'-( '+v+' )':'-';state.expression=input.value;input.focus();return;}if(k==='reciprocal'){input.value=v?'1/('+v+')':'1/(';state.expression=input.value;input.focus();return;}
  input.value=v.slice(0,start)+insert+v.slice(end);input.focus();input.setSelectionRange(start+insert.length,start+insert.length);state.expression=input.value;
 }
 document.addEventListener('input',e=>{if(e.target.id==='calc-expression'){state.expression=e.target.value;dirty();}if(e.target.id==='history-search'){state.historySearch=e.target.value;$('#history-list').innerHTML=historyRows();}});
 document.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const id=e.target.id;if(id==='calc-expression'){e.preventDefault();calculate();}else if(id==='equation-input'){e.preventDefault();runEquation();}else if(id.startsWith('system-')){e.preventDefault();runSystem();}else if(id==='practice-answer'){e.preventDefault();checkPractice();}else if(['graph-expression','graph-min','graph-max'].includes(id)){e.preventDefault();plot();}});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;capture();
  if(a==='theme'){state.theme=state.theme==='dark'?'light':'dark';write('theme',state.theme);render();}
  else if(a==='privacy'){const d=$('#info-dialog');if(d.showModal)d.showModal();else d.setAttribute('open','');}
  else if(a==='close-dialog')$('#info-dialog').close();
  else if(a==='calc-mode'){state.calcMode=el.dataset.mode;render();}
  else if(a==='angle'){state.angle=el.dataset.angle;write('angle',state.angle);$('#screen-angle').textContent=state.angle.toUpperCase()+' MODE';document.querySelectorAll('[data-action="angle"]').forEach(b=>b.classList.toggle('active',b.dataset.angle===state.angle));state.answer='—';$('#calc-answer').textContent='—';if(state.expression)calculate(false);}
  else if(a==='key')key(el.dataset.key);
  else if(a==='copy-calc'){if(state.answer==='—'){toast('Calculate a valid result first.');return;}copy(state.expression+' = '+state.answer);}
  else if(a==='complex-solve')complexSolve();
  else if(a==='solver-mode'){state.solverMode=el.dataset.mode;render();}
  else if(a==='solve-equation')runEquation();
  else if(a==='reset-equation'){$('#equation-input').value='';state.equation='';$('#solution').innerHTML='';$('#solver-error').innerHTML='';lastSolution=null;$('#equation-input').focus();}
  else if(a==='example-equation'){$('#equation-input').value=el.dataset.value;runEquation(false);}
  else if(a==='copy-solution'){if(lastSolution)copy(lastSolution.copy);}
  else if(a==='system-count'){state.systemN=Number(el.dataset.count);state.systemInputs=state.systemN===3?['x + y + z = 6','2x - y + z = 3','x + 2y - z = 2']:['x + y = 7','x - y = 1'];render();}
  else if(a==='solve-system')runSystem();
  else if(a==='example-system'){state.systemInputs=state.systemN===3?['x + y + z = 6','2x - y + z = 3','x + 2y - z = 2']:['x + y = 7','x - y = 1'];render();runSystem();}
  else if(a==='plot')plot();
  else if(a==='graph-preset'){$('#graph-expression').value=el.dataset.value;if(el.dataset.value==='sin(x)'){$('#graph-min').value=-2*Math.PI;$('#graph-max').value=2*Math.PI;}else if(el.dataset.value==='sqrt(x)'){$('#graph-min').value=0;$('#graph-max').value=10;}else{$('#graph-min').value=-5;$('#graph-max').value=5;}plot();}
  else if(a==='graph-reset'){$('#graph-min').value=-5;$('#graph-max').value=5;plot();}
  else if(a==='graph-zoom'){const lo=Number($('#graph-min').value),hi=Number($('#graph-max').value),mid=(lo+hi)/2,half=(hi-lo)/2*Number(el.dataset.factor);$('#graph-min').value=mid-half;$('#graph-max').value=mid+half;plot();}
  else if(a==='save-graph'){if(!graphResult){toast('Plot a valid function first.');return;}save({kind:'Graph',input:state.graphExpression,answer:`x from ${fmt(state.xmin)} to ${fmt(state.xmax)}`,range:[state.xmin,state.xmax]});toast('Graph saved to history.');}
  else if(a==='open-lesson'){state.lesson=el.dataset.id;state.practiceIndex=0;if(state.route!=='learn')location.hash='learn';else{render();window.scrollTo(0,0);}}
  else if(a==='back-lessons'){state.lesson=null;render();window.scrollTo(0,0);}
  else if(a==='next-practice'){state.practiceIndex=(state.practiceIndex+1)%3;render();}
  else if(a==='check-practice')checkPractice();
  else if(a==='lesson-tool'){const l=el.dataset.id;if(['linear','quadratic','systems'].includes(l)){state.solverMode=l==='systems'?'system':'equation';state.equation=l==='linear'?'3x + 7 = 22':'x^2 - 5x + 6 = 0';location.hash='solver';}else if(l==='graphs'){location.hash='graph';}else{state.calcMode=l==='complex'?'complex':'scientific';state.expression=({fractions:'1/3 + 1/4',powers:'log(1000) + 2^3',trig:'sin(30)*20'})[l]||state.expression;if(l==='trig'){state.angle='deg';write('angle','deg');}state.answer='—';location.hash='calculator';}}
  else if(a==='history-filter'){state.historyFilter=el.dataset.filter;render();}
  else if(['star','delete-history','copy-history','reuse'].includes(a)){const h=state.history.find(h=>h.id===el.dataset.id);if(!h)return;
   if(a==='star'){h.star=!h.star;write('history',state.history);render();}else if(a==='delete-history'){state.history=state.history.filter(x=>x.id!==h.id);write('history',state.history);render();}else if(a==='copy-history')copy(h.input+'\n'+h.answer);else if(h.kind==='Equation'){state.equation=h.input;state.solverMode='equation';location.hash='solver';}else if(h.kind==='Graph'){state.graphExpression=h.input;if(Array.isArray(h.range)){[state.xmin,state.xmax]=h.range;}location.hash='graph';}else if(h.kind==='Linear system'){state.systemInputs=h.input.split(' · ');state.systemN=state.systemInputs.length;state.solverMode='system';location.hash='solver';}else if(h.kind==='Complex number'){state.calcMode='complex';if(Array.isArray(h.components)&&h.components.length===4&&h.components.every(Number.isFinite)){state.complexInputs=h.components;state.complexOp=['+','-','*','/'].includes(h.operation)?h.operation:'+';}location.hash='calculator';}else{state.expression=h.input;state.answer=h.answer;state.calcMode='scientific';location.hash='calculator';}}
  else if(a==='clear-history'){if(confirm('Delete all calculations and bookmarks from this device?')){state.history=[];write('history',[]);render();toast('History cleared.');}}
  else if(a==='reset-progress'){if(confirm('Reset all practice progress on this device?')){state.progress={};write('progress',{});render();toast('Practice progress reset.');}}
 });
 window.addEventListener('hashchange',route);route();
 if('serviceWorker' in navigator && ['https:','http:'].includes(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
